apiVersion: v2
appVersion: 20.0.3
description: Keycloak.X - Open Source Identity and Access Management for Modern Applications and Services
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_logo_200px.svg
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - oauth
  - ldap
  - keycloakx
  - quarkus
maintainers:
  - email: thomas.darimont+github@gmail.com
    name: thomasdarimont
name: keycloakx
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/keycloak/keycloak/tree/main/quarkus/container
version: 2.1.1
annotations:
  provenance: |
    - 2.1.1:
        upstreamIndexEntry:
          apiVersion: v2
          appVersion: 20.0.3
          created: "2023-02-03T16:04:00.033141832Z"
          description: Keycloak.X - Open Source Identity and Access Management for Modern Applications and Services
          digest: 1ae37a17d10d159f793dc6a42ec4182bb230fccadd092badb45a36986fe45d71
          home: https://www.keycloak.org/
          icon: https://www.keycloak.org/resources/images/keycloak_logo_200px.svg
          keywords:
            - sso
            - idm
            - openid connect
            - saml
            - kerberos
            - oauth
            - ldap
            - keycloakx
            - quarkus
          maintainers:
            - email: thomas.darimont+github@gmail.com
              name: thomasdarimont
          name: keycloakx
          sources:
            - https://github.com/codecentric/helm-charts
            - https://github.com/keycloak/keycloak/tree/main/quarkus/container
          urls:
            - https://github.com/codecentric/helm-charts/releases/download/keycloakx-2.1.1/keycloakx-2.1.1.tgz
          version: 2.1.1
