name: Release Charts

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Was added to fix error https://github.com/helm/chart-releaser-action/issues/74
      - name: Add dependency helm repos
        run: |
          for dir in $(ls -d charts/*/*); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n 1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
            for subdir in $(ls -d $dir/charts/*); do
              helm dependency list $subdir 2> /dev/null | tail +2 | head -n 1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
            done
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts/*
        env:
          CR_TOKEN: "${{ secrets.GIT_TOKEN }}"